general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  #  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]


[window]
opacity = 0.9

padding.x = 10
padding.y = 10
dynamic_padding = true
blur = true

decorations = "Buttonless"
decorations_theme_variant = "Light" # "Dark"

[font]
size = 15.0
normal.family = "DejaVuSansM Nerd Font Mono"
bold.family = "DejaVuSansM Nerd Font Mono"
italic.family = "DejaVuSansM Nerd Font Mono"
bold_italic.family = "DejaVuSansM Nerd Font Mono"


[selection]
save_to_clipboard = true


